language: c

compiler: gcc

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake git gfortran libopenmpi-dev openmpi-bin

before_script:
  - cmake --version
  - git fetch --depth 9999999
  - git describe --dirty
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest --output-on-failure

notifications:
  email:
    - bfam@bfam@librelist.com
  on_success: change
  on_failure: always
